"""Writes the tree, runs git init.

Every file that reaches disk comes from :func:`file_table`, and :func:`plan`
reads the same table without touching disk. That is why the two cannot drift.
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import List, Tuple, Union

from . import templates
from .spec import Spec

#: Used only when git has no identity of its own to commit with.
FALLBACK_IDENTITY = ("degenerator", "degenerator@localhost")


class ScaffoldError(Exception):
    """A refusal the user can read without a traceback."""


@dataclass
class Result:
    """What one ``new`` run actually did."""

    out: Path
    files: List[str]
    bytes: int
    git: str


def file_table(spec: Spec) -> List[Tuple[str, str]]:
    """Every generated file as ``(relative path, text)``. The only source."""
    return templates.render(spec)


def plan(spec: Spec) -> List[str]:
    """The paths ``new`` would write, in order. Touches nothing."""
    return [path for path, _ in file_table(spec)]


def write(
    spec: Spec,
    out: Union[str, Path],
    force: bool = False,
    no_git: bool = True,
) -> Result:
    """Write the tree for ``spec`` into ``out``."""
    out = Path(out)
    if out.exists():
        if not out.is_dir():
            raise ScaffoldError("{0} exists and is not a directory".format(out))
        if any(out.iterdir()) and not force:
            raise ScaffoldError("{0} is not empty: pass --force to write over it".format(out))

    written: List[str] = []
    total = 0
    for relative, text in file_table(spec):
        target = out / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        data = text.encode("utf-8")
        # Bytes, not text: no platform newline translation, so the tree is the
        # same on Windows as it is in the container.
        with open(target, "wb") as handle:
            handle.write(data)
        written.append(relative)
        total += len(data)

    for directory in templates.DIRECTORIES:
        (out / directory).mkdir(parents=True, exist_ok=True)

    git = "skipped" if no_git else init_git(out, spec)
    return Result(out=out, files=written, bytes=total, git=git)


def init_git(out: Path, spec: Spec) -> str:
    """``git init`` plus the first commit. A missing git never fails the run."""
    if shutil.which("git") is None:
        return "unavailable (git not found)"
    # spec.filename, not spec.source: this message ends up in a history that
    # gets pushed, and an absolute path names the user's home directory.
    message = "{0}: generated by degenerator from {1}".format(spec.title, spec.filename)
    try:
        _git(out, "init", "-q")
        # Deterministic branch name on any git version, with no dependency on
        # the user's init.defaultBranch.
        _git(out, "symbolic-ref", "HEAD", "refs/heads/main")
        _git(out, "add", "-A")
        if not _git_out(out, "status", "--porcelain").strip():
            # A --force re-run that produced the same bytes. Nothing to record.
            return "initialised · nothing to commit"
        try:
            _git(out, "commit", "-q", "-m", message)
        except subprocess.CalledProcessError:
            # Almost always a machine with no user.name/user.email configured.
            _git(
                out,
                "-c",
                "user.name={0}".format(FALLBACK_IDENTITY[0]),
                "-c",
                "user.email={0}".format(FALLBACK_IDENTITY[1]),
                "commit",
                "-q",
                "-m",
                message,
            )
    except subprocess.CalledProcessError as exc:
        return "initialised · commit failed (git exit {0})".format(exc.returncode)
    except OSError as exc:
        return "unavailable ({0})".format(exc.strerror or exc)
    return "initialised · 1 commit"


def _git(cwd: Path, *args: str) -> None:
    subprocess.run(
        ("git",) + args,
        cwd=str(cwd),
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def _git_out(cwd: Path, *args: str) -> str:
    done = subprocess.run(
        ("git",) + args,
        cwd=str(cwd),
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
    )
    return done.stdout.decode("utf-8", "replace")
