"""Every generated file, as one flat table.

``TEMPLATES`` is the single source of truth for what a generated repo contains.
:func:`render` is deterministic: no timestamps, no randomness, no iteration
over anything unordered. Run it twice on the same spec, get the same bytes.
"""

from __future__ import annotations

from typing import Callable, List, Tuple

from .spec import SPOT_ONLY, Spec

TAB = "\t"


# --- small helpers -------------------------------------------------------


def _num(value) -> str:
    """A number as it should read in generated source: ``3``, not ``3.0``."""
    if isinstance(value, int):
        return str(value)
    return repr(round(value, 10))


def _pct(value) -> str:
    """``0.05`` -> ``5%``, for prose only. Code always gets the raw number."""
    scaled = value * 100
    if scaled == int(scaled):
        return "{0}%".format(int(scaled))
    return "{0}%".format(round(scaled, 6))


def _docsafe(text: str) -> str:
    """Neutralise free text before it is embedded in generated source.

    A spec is a file, and a file can come from someone else. Nothing a spec
    carries may close a string, start an escape, or reach a new line in
    generated Python: that would be code execution the moment the user runs
    `make test` on the repo we just told them to trust.

    Values that must survive verbatim are emitted through repr(), not here.
    """
    cleaned = text.replace("\\", "/").replace('"', "'")
    return cleaned.replace("\r", " ").replace("\n", " ")


def _class_name(venue: str) -> str:
    return "{0}Venue".format(venue.capitalize())


def _list_literal(items) -> str:
    return "[{0}]".format(", ".join(repr(item) for item in items))


def _block(lines) -> str:
    return "\n".join(lines) + "\n"


# --- the generated files -------------------------------------------------

#: Per venue: the comment lines that go above the fields, and the field names
#: themselves. No entry here may name a private key, a mnemonic, or a seed —
#: a generated .env.example is the last place that should teach anyone to put
#: a signing key in a file.
CREDENTIALS = {
    "hyperliquid": ((), ("HYPERLIQUID_ACCOUNT_ADDRESS", "HYPERLIQUID_API_SECRET")),
    "dydx": (
        (),
        (
            "DYDX_ACCOUNT_ADDRESS",
            "DYDX_API_KEY",
            "DYDX_API_SECRET",
            "DYDX_API_PASSPHRASE",
        ),
    ),
    "robinhood": (
        (
            "Reading robinhood chain needs an RPC endpoint and nothing else.",
            "Signing is deliberately not part of this repo: a key does not",
            "belong in a file like this one, and a generated repo has no",
            "business teaching you otherwise.",
        ),
        ("ROBINHOOD_RPC_URL",),
    ),
    "paper": ((), ()),
}


def _readme(spec: Spec) -> str:
    caps = (
        ("max_position", "{0} of equity".format(_pct(spec.max_position))),
        ("stop_loss", "{0} per position".format(_pct(spec.stop_loss))),
        ("leverage", "{0}x".format(_num(spec.leverage))),
        ("cash", "{0} starting paper equity".format(_num(spec.cash))),
    )
    out = [
        "# {0}".format(spec.title),
        "",
        "Generated by degenerator from `{0}`.".format(spec.filename),
        "",
        "## What it trades",
        "",
        "- venue: `{0}` — paper-mode adapter, no network, no money".format(spec.venue),
        "- pairs: {0}".format(", ".join("`{0}`".format(pair) for pair in spec.pairs)),
        "- timeframe: `{0}`".format(spec.timeframe),
    ]
    if spec.venue in SPOT_ONLY:
        out.append(
            "- {0} chain is spot only: there is no leverage to ask for, and the "
            "generated adapter models swaps against a pool rather than order "
            "book fills.".format(spec.venue)
        )
    out += [
        "",
        "## The caps",
        "",
        "Every number below traces back to a line in the spec or to a documented",
        "default. `src/risk.py` is the only file allowed to say no, and",
        "`tests/test_risk.py` asserts these exact numbers.",
        "",
        "| cap | value | where it came from |",
        "| --- | --- | --- |",
    ]
    for key, shown in caps:
        out.append("| `{0}` | {1} | `{2}` |".format(key, shown, spec.origin(key)))
    out += [
        "",
        "## Rules, copied from the spec",
        "",
        "Verbatim. They live in `src/strategy.py` as comments — degenerator does",
        "not turn English into code, so writing the logic is your job.",
        "",
    ]
    out += ["- {0}".format(rule) for rule in spec.rules]
    if spec.extras:
        out += [
            "",
            "## Other keys from the spec",
            "",
            "Kept as written, unused by the generated code. Nothing a human wrote",
            "is dropped on the floor.",
            "",
        ]
        out += ["- `{0}`: {1}".format(key, value) for key, value in spec.extras.items()]
    out += [
        "",
        "## Run it",
        "",
        "```",
        "cp .env.example .env",
        "make test",
        "make run",
        "```",
        "",
        "`make image` builds the container; `compose.yml` mounts `runs/` so the",
        "run records survive the container.",
        "",
        "## Safety",
        "",
        "The venue adapter is a paper-mode stub: placeholder prices and fake fills,",
        "so the loop runs end to end without touching an exchange. It refuses to",
        "construct with `live=True`. The live order path is deliberately left to you",
        "to implement and review.",
        "",
        "The caps above are applied, not judged: degenerator copies what the spec",
        "said and never second-guesses it, so nothing capped `leverage` at",
        "{0}x. Paper mode means nothing is at risk here — the number is yours to".format(
            _num(spec.leverage)
        ),
        "sanity-check before this goes anywhere near an exchange.",
        "",
        "Nothing here is financial advice.",
    ]
    return _block(out)


def _env_example(spec: Spec) -> str:
    out = [
        "# Copy to .env, then fill it in. .env is gitignored; keys never go in git.",
        "# The generated adapter is paper-mode and reads none of these — they are",
        "# here for the live path you write yourself.",
        "",
        "LIVE=false",
        "",
    ]
    note, keys = CREDENTIALS[spec.venue]
    if keys:
        out.append("# {0}".format(spec.venue))
        out += ["# {0}".format(line) for line in note]
        out += ["{0}=".format(key) for key in keys]
    else:
        out.append("# the paper venue needs no credentials at all.")
    return _block(out)


def _gitignore(spec: Spec) -> str:
    return _block(
        [
            ".env",
            "__pycache__/",
            "*.py[cod]",
            ".venv/",
            "",
            "# run records are written by the bot, never edited by hand",
            "runs/*.json",
            "runs/*.log",
        ]
    )


def _requirements(spec: Spec) -> str:
    return _block(
        [
            "# Intentionally empty.",
            "#",
            "# This bot runs on the Python standard library alone: nothing to pin,",
            "# nothing to audit, nothing to wake up broken. If you add a dependency,",
            "# you own it.",
        ]
    )


def _makefile(spec: Spec) -> str:
    return _block(
        [
            ".PHONY: run test image",
            "",
            "run:",
            TAB + "python src/main.py",
            "",
            "test:",
            TAB + "python -m unittest discover -s tests -q",
            "",
            "image:",
            TAB + "docker build -t {0} .".format(spec.slug),
        ]
    )


def _dockerfile(spec: Spec) -> str:
    return _block(
        [
            "# Multi-stage, though there is nothing to compile: the build stage only",
            "# proves the sources import cleanly before they reach the runtime image.",
            "FROM python:3.12-slim AS build",
            "WORKDIR /app",
            "COPY . .",
            "RUN python -m compileall -q src tests",
            "",
            "FROM python:3.12-slim AS runtime",
            "WORKDIR /app",
            "ENV PYTHONUNBUFFERED=1 PYTHONDONTWRITEBYTECODE=1",
            "COPY --from=build /app /app",
            "RUN useradd --create-home --uid 10001 bot && chown -R bot:bot /app",
            "USER bot",
            'CMD ["python", "src/main.py"]',
        ]
    )


def _compose(spec: Spec) -> str:
    return _block(
        [
            "services:",
            "  bot:",
            "    build: .",
            "    image: {0}".format(spec.slug),
            "    env_file: .env",
            "    volumes:",
            "      # run records outlive the container",
            "      - ./runs:/app/runs",
            "    restart: \"no\"",
        ]
    )


def _ci(spec: Spec) -> str:
    return _block(
        [
            "name: ci",
            "",
            "on:",
            "  push:",
            "  pull_request:",
            "",
            "jobs:",
            "  test:",
            "    runs-on: ubuntu-latest",
            "    steps:",
            "      - uses: actions/checkout@v4",
            "      - uses: actions/setup-python@v5",
            "        with:",
            '          python-version: "3.12"',
            "      - name: unittest",
            "        run: python -m unittest discover -s tests -q",
            "",
            "  image:",
            "    runs-on: ubuntu-latest",
            "    steps:",
            "      - uses: actions/checkout@v4",
            "      - name: docker build",
            "        run: docker build -t {0} .".format(spec.slug),
        ]
    )


def _risk(spec: Spec) -> str:
    return _block(
        [
            '"""The only file allowed to say no.',
            "",
            "Every number here traces back to a line in the spec or to a documented",
            "default — the comment above each one says which. Nothing else in this",
            "repo may raise a cap; everything else asks this module first.",
            '"""',
            "",
            "# {0}".format(spec.origin("max_position")),
            "MAX_POSITION = {0}".format(_num(spec.max_position)),
            "",
            "# {0}".format(spec.origin("stop_loss")),
            "STOP_LOSS = {0}".format(_num(spec.stop_loss)),
            "",
            "# {0}".format(spec.origin("leverage")),
            "LEVERAGE = {0}".format(_num(spec.leverage)),
            "",
            "# {0}".format(spec.origin("cash")),
            "CASH = {0}".format(_num(spec.cash)),
            "",
            "",
            "def max_notional(equity):",
            '    """The largest notional one position may carry, caps included."""',
            "    return equity * MAX_POSITION * LEVERAGE",
            "",
            "",
            "def stop_price(entry, side):",
            '    """Where a position gets cut, per the spec\'s stop_loss."""',
            '    if side == "long":',
            "        return entry * (1.0 - STOP_LOSS)",
            '    if side == "short":',
            "        return entry * (1.0 + STOP_LOSS)",
            "    raise ValueError(\"side must be 'long' or 'short', got {0!r}\".format(side))",
            "",
            "",
            "def check(order, equity):",
            '    """Return a refusal string, or None when the order is allowed."""',
            '    notional = order["notional"]',
            "    if notional <= 0:",
            '        return "notional must be positive, got {0}".format(notional)',
            "    cap = max_notional(equity)",
            "    if notional > cap:",
            '        return "notional {0:.2f} over the cap {1:.2f} (max_position {2}, leverage {3})".format(',
            "            notional, cap, MAX_POSITION, LEVERAGE",
            "        )",
            '    if order.get("leverage", LEVERAGE) > LEVERAGE:',
            '        return "leverage {0} over the cap {1}".format(order["leverage"], LEVERAGE)',
            "    return None",
        ]
    )


def _strategy(spec: Spec) -> str:
    out = [
        '"""Signals in, orders out.',
        "",
        "The rules below are copied verbatim from the spec. degenerator does not",
        "turn English into code on purpose: you write the logic, you own the trades.",
        '"""',
        "",
        "PAIRS = {0}".format(_list_literal(spec.pairs)),
        "TIMEFRAME = {0!r}".format(spec.timeframe),
        "",
        "# --- rules from the spec, verbatim ---------------------------------",
    ]
    out += ["# {0}".format(rule) for rule in spec.rules]
    out += [
        "# -------------------------------------------------------------------",
        "",
        "",
        "def decide(pair, price, position=None):",
        '    """Return an intent dict like {"side": "long"}, or None to stand still.',
        "",
        "    Placeholder: it stands still. Implement the rules above here, on the",
        "    {0} timeframe, and size the result through risk.py.".format(
            _docsafe(spec.timeframe)
        ),
        '    """',
        "    return None",
    ]
    return _block(out)


def _venue_base(spec: Spec) -> str:
    return _block(
        [
            '"""The interface every venue answers.',
            "",
            "Paper mode only. Constructing an adapter with live=True is refused: the",
            "live order path is left to you to implement and review.",
            '"""',
            "",
            "",
            "class Venue:",
            '    """Fetch a price, submit an order, list what is open."""',
            "",
            '    name = "base"',
            "",
            "    def __init__(self, live=False):",
            "        if live:",
            "            raise RuntimeError(",
            '                "{0} is a paper-mode stub: the live order path is "',
            '                "deliberately not implemented. Write it and review it "',
            '                "yourself before any of this touches money.".format(',
            "                    type(self).__name__",
            "                )",
            "            )",
            "        self.live = False",
            "",
            "    def price(self, pair):",
            '        """Last price for a pair."""',
            "        raise NotImplementedError",
            "",
            "    def submit(self, order):",
            '        """Send an order dict, return a fill dict."""',
            "        raise NotImplementedError",
            "",
            "    def positions(self):",
            '        """Everything currently open."""',
            "        raise NotImplementedError",
        ]
    )


def _venue_adapter(spec: Spec) -> str:
    cls = _class_name(spec.venue)
    spot = spec.venue in SPOT_ONLY
    head = [
        '"""{0} adapter, paper mode.'.format(spec.venue),
        "",
        "Placeholder prices and fake fills, so the loop runs end to end without",
        "touching an exchange. Nothing here opens a socket. The live order path",
        "is yours to write and review.",
    ]
    if spot:
        head += [
            "",
            "Robinhood Chain is an Ethereum layer-2 on Arbitrum Orbit, and it is spot",
            "only: there is no leverage to ask for and no order book to sit in. The",
            "fills below model a swap against a pool, which is why each one carries",
            "model=swap. Writing the actual swap — routing, slippage, signing — is",
            "yours, and none of it lives here.",
        ]
    return _block(
        head
        + [
            '"""',
            "",
            "import hashlib",
            "",
            "from venue.base import Venue",
            "",
            "",
            "def placeholder_price(pair):",
            '    """A stable made-up price. Deterministic per pair, worth nothing."""',
            '    digest = hashlib.sha256(pair.encode("utf-8")).digest()',
            '    return round(10.0 + (int.from_bytes(digest[:4], "big") % 100000) / 100.0, 2)',
            "",
            "",
            "class {0}(Venue):".format(cls),
            "",
            '    name = "{0}"'.format(spec.venue),
            "",
            "    def __init__(self, live=False):",
            "        super().__init__(live=live)",
            "        self._fills = []",
            "",
            "    def price(self, pair):",
            "        return placeholder_price(pair)",
            "",
            "    def submit(self, order):",
            '        """Fake a fill at the placeholder price. No network, no money."""',
            '        price = order.get("price") or self.price(order["pair"])',
            "        fill = {",
            '            "status": "filled",',
            '            "venue": self.name,',
            '            "pair": order["pair"],',
            '            "side": order["side"],',
            '            "notional": order["notional"],',
            '            "price": price,',
            '            "fee": 0.0,',
            '            "paper": True,',
        ]
        + (['            "model": "swap",'] if spot else [])
        + [
            "        }",
            "        self._fills.append(fill)",
            "        return fill",
            "",
            "    def positions(self):",
            "        return list(self._fills)",
        ]
    )


def _main(spec: Spec) -> str:
    cls = _class_name(spec.venue)
    return _block(
        [
            '"""One pass: fetch, decide, size, submit.',
            "",
            "Paper mode. `make run` calls this; it writes a run record into runs/ and",
            "exits. Loop it from cron or a supervisor if you want it to keep going.",
            '"""',
            "",
            "import json",
            "import sys",
            "from datetime import datetime, timezone",
            "from pathlib import Path",
            "",
            "SRC = Path(__file__).resolve().parent",
            "if str(SRC) not in sys.path:",
            "    sys.path.insert(0, str(SRC))",
            "",
            "import risk  # noqa: E402  (after the sys.path line above)",
            "import strategy  # noqa: E402",
            "from venue.{0} import {1}  # noqa: E402".format(spec.venue, cls),
            "",
            "RUNS = SRC.parent / \"runs\"",
            "",
            "",
            "def run_once(venue=None, equity=risk.CASH):",
            '    """Walk every pair once and return what happened."""',
            "    venue = venue or {0}()".format(cls),
            "    submitted = []",
            "    skipped = []",
            "    for pair in strategy.PAIRS:",
            "        price = venue.price(pair)  # fetch",
            "        intent = strategy.decide(pair, price)  # decide",
            "        if intent is None:",
            '            skipped.append({"pair": pair, "why": "no signal"})',
            "            continue",
            "        order = {  # size",
            '            "pair": pair,',
            '            "side": intent["side"],',
            '            "notional": risk.max_notional(equity),',
            '            "price": price,',
            "        }",
            "        refusal = risk.check(order, equity)  # the only no",
            "        if refusal:",
            '            skipped.append({"pair": pair, "why": refusal})',
            "            continue",
            "        submitted.append(venue.submit(order))  # submit",
            "    return {",
            '        "venue": venue.name,',
            '        "equity": equity,',
            '        "paper": True,',
            '        "submitted": submitted,',
            '        "skipped": skipped,',
            "    }",
            "",
            "",
            "def main():",
            "    record = run_once()",
            "    now = datetime.now(timezone.utc)",
            '    record["at"] = now.isoformat(timespec="seconds")',
            "    RUNS.mkdir(parents=True, exist_ok=True)",
            '    path = RUNS / "run-{0}.json".format(now.strftime("%Y%m%dT%H%M%S"))',
            '    path.write_text(json.dumps(record, indent=2) + "\\n", encoding="utf-8")',
            "    print(",
            '        "{0}: {1} submitted, {2} skipped -> {3}".format(',
            '            record["venue"], len(record["submitted"]), len(record["skipped"]), path',
            "        )",
            "    )",
            "    return 0",
            "",
            "",
            'if __name__ == "__main__":',
            "    raise SystemExit(main())",
        ]
    )


def _test_risk(spec: Spec) -> str:
    cls = _class_name(spec.venue)
    return _block(
        [
            '"""The caps from the spec, asserted.',
            "",
            "If someone edits src/risk.py to trade bigger than {0} allowed,".format(
                _docsafe(spec.filename)
            ),
            "this test fails. That is the whole point of it.",
            '"""',
            "",
            "import sys",
            "import unittest",
            "from pathlib import Path",
            "",
            'sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))',
            "",
            "import main  # noqa: E402  (after the sys.path line above)",
            "import risk  # noqa: E402",
            "import strategy  # noqa: E402",
            "from venue.{0} import {1}  # noqa: E402".format(spec.venue, cls),
            "",
            "",
            "class TestCapsFromTheSpec(unittest.TestCase):",
            "",
            "    def test_caps_are_exactly_what_the_spec_said(self):",
            "        self.assertAlmostEqual(risk.MAX_POSITION, {0})".format(_num(spec.max_position)),
            "        self.assertAlmostEqual(risk.STOP_LOSS, {0})".format(_num(spec.stop_loss)),
            "        self.assertAlmostEqual(risk.LEVERAGE, {0})".format(_num(spec.leverage)),
            "        self.assertAlmostEqual(risk.CASH, {0})".format(_num(spec.cash)),
            "",
            "    def test_pairs_and_timeframe_are_the_spec_ones(self):",
            "        self.assertEqual(strategy.PAIRS, {0})".format(_list_literal(spec.pairs)),
            "        self.assertEqual(strategy.TIMEFRAME, {0!r})".format(spec.timeframe),
            "",
            "    def test_max_notional_scales_with_equity(self):",
            "        self.assertAlmostEqual(",
            "            risk.max_notional(risk.CASH),",
            "            risk.CASH * risk.MAX_POSITION * risk.LEVERAGE,",
            "        )",
            "",
            "    def test_stop_price_sits_a_stop_loss_away(self):",
            '        self.assertAlmostEqual(risk.stop_price(100.0, "long"), 100.0 * (1 - risk.STOP_LOSS))',
            '        self.assertAlmostEqual(risk.stop_price(100.0, "short"), 100.0 * (1 + risk.STOP_LOSS))',
            "        with self.assertRaises(ValueError):",
            '            risk.stop_price(100.0, "sideways")',
            "",
            "    def test_an_order_at_the_cap_is_allowed(self):",
            '        order = {"pair": "BTC", "side": "long", "notional": risk.max_notional(risk.CASH)}',
            "        self.assertIsNone(risk.check(order, risk.CASH))",
            "",
            "    def test_an_order_over_the_cap_is_refused(self):",
            "        order = {",
            '            "pair": "BTC",',
            '            "side": "long",',
            '            "notional": risk.max_notional(risk.CASH) * 1.01,',
            "        }",
            "        self.assertIn(\"over the cap\", risk.check(order, risk.CASH))",
            "",
            "    def test_too_much_leverage_is_refused(self):",
            "        order = {",
            '            "pair": "BTC",',
            '            "side": "long",',
            '            "notional": 1.0,',
            '            "leverage": risk.LEVERAGE + 1,',
            "        }",
            '        self.assertIn("leverage", risk.check(order, risk.CASH))',
            "",
            "",
            "class TestPaperOnly(unittest.TestCase):",
            "",
            "    def test_live_is_refused(self):",
            "        with self.assertRaises(RuntimeError) as caught:",
            "            {0}(live=True)".format(cls),
            '        self.assertIn("paper-mode stub", str(caught.exception))',
            "",
            "    def test_a_fill_is_fake_and_says_so(self):",
            "        venue = {0}()".format(cls),
            '        fill = venue.submit({"pair": "BTC", "side": "long", "notional": 1.0})',
            '        self.assertTrue(fill["paper"])',
            '        self.assertEqual(fill["status"], "filled")',
            "        self.assertEqual(venue.positions(), [fill])",
            "",
            "",
            "class TestOnePass(unittest.TestCase):",
            "",
            "    def test_the_loop_runs_end_to_end(self):",
            "        record = main.run_once(venue={0}(), equity=risk.CASH)".format(cls),
            '        self.assertTrue(record["paper"])',
            '        self.assertEqual(record["venue"], {0!r})'.format(spec.venue),
            "        seen = [row[\"pair\"] for row in record[\"submitted\"]] + [",
            '            row["pair"] for row in record["skipped"]',
            "        ]",
            "        self.assertEqual(sorted(seen), sorted(strategy.PAIRS))",
            "",
            "",
            'if __name__ == "__main__":',
            "    unittest.main()",
        ]
    )


# --- the table -----------------------------------------------------------

#: (path template, renderer). The venue adapter is the only path that varies.
TEMPLATES: List[Tuple[str, Callable[[Spec], str]]] = [
    ("README.md", _readme),
    (".env.example", _env_example),
    (".gitignore", _gitignore),
    ("requirements.txt", _requirements),
    ("Makefile", _makefile),
    ("Dockerfile", _dockerfile),
    ("compose.yml", _compose),
    (".github/workflows/ci.yml", _ci),
    ("src/main.py", _main),
    ("src/strategy.py", _strategy),
    ("src/risk.py", _risk),
    ("src/venue/base.py", _venue_base),
    ("src/venue/{venue}.py", _venue_adapter),
    ("tests/test_risk.py", _test_risk),
]

#: Directories created empty. git will not track them; the bot fills them in.
DIRECTORIES = ("runs",)


def render(spec: Spec) -> List[Tuple[str, str]]:
    """Every file for this spec, as ``(relative path, text)``, in table order."""
    rendered = []
    for path_template, renderer in TEMPLATES:
        path = path_template.format(venue=spec.venue)
        text = renderer(spec)
        if not text.endswith("\n"):
            text += "\n"
        rendered.append((path, text))
    return rendered
